import sharp from "sharp";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import opentype from "opentype.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT_PATH = resolve(__dirname, "fonts", "Roboto-Bold.ttf");

// Load font once at startup — opentype.js reads the TTF and can generate SVG paths
// for any string, so the SVG renderer (librsvg) never needs a font at all.
let _font = null;
function getFont() {
  if (!_font) {
    try {
      const buf = readFileSync(FONT_PATH);
      _font = opentype.parse(buf.buffer);
    } catch {
      _font = null;
    }
  }
  return _font;
}

// Fallback teaser pool — deterministic per article title.
const TEASER_POOL = [
  "NIMENI NU S-A ASTEPTAT!",
  "A IESIT TOTUL LA IVEALA!",
  "BOMBA ZILEI!",
  "TOTUL S-A DAT PESTE CAP!",
  "SOC TOTAL!",
  "DEZVALUIRE EXPLOZIVA!",
  "NIMENI NU STIA!",
  "ADEVARUL A IESIT LA SUPRAFATA!",
  "INCREDIBIL CE S-A INTAMPLAT!",
  "TOATA LUMEA VORBESTE!",
  "MARE SURPRIZA!",
  "SITUATIE FARA PRECEDENT!",
  "REACTIE NEASTEPTATA!",
  "DECIZIE DE ULTIMA ORA!",
  "S-A AFLAT TOTUL!",
  "LOVITURA ZILEI!",
  "SCHIMBARE MAJORA!",
  "NIMENI NU SE ASTEPTA!",
  "TOTUL A EXPLODAT!",
  "ANUNT BOMBA!",
];

export function pickFallbackTeaser(title) {
  const str = String(title || "");
  let hash = 0;
  for (let i = 0; i < str.length; i++) hash = (hash * 31 + str.charCodeAt(i)) >>> 0;
  return TEASER_POOL[hash % TEASER_POOL.length];
}

const DEFAULT_SIZE = 1080;
const FETCH_TIMEOUT_MS = 15000;
const BAR_HEIGHT = 120;
const FONT_SIZE = 52;

/** Strip diacritics and uppercase — safe fallback if font lacks glyphs. */
function normaliseText(text) {
  return String(text || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .trim();
}

/** Word-wrap into at most maxLines lines, each ≤ maxChars characters. */
function wrapText(text, maxChars, maxLines) {
  const words = String(text || "").trim().split(/\s+/);
  const lines = [];
  let current = "";
  for (const word of words) {
    if (lines.length >= maxLines) break;
    const test = current ? `${current} ${word}` : word;
    if (test.length <= maxChars) {
      current = test;
    } else {
      if (current) {
        lines.push(current);
        current = word.slice(0, maxChars);
      } else {
        lines.push(word.slice(0, maxChars));
        current = "";
      }
    }
  }
  if (current && lines.length < maxLines) lines.push(current);
  return lines;
}

/**
 * Converts a text string to an SVG <path> element using the TTF font.
 * Returns null if the font failed to load.
 */
function textToSvgPath(text, x, y, fontSize, fill = "white") {
  const font = getFont();
  if (!font) return null;
  try {
    const path = font.getPath(text, x, y, fontSize);
    const d = path.toPathData(2);
    if (!d) return null;
    return `<path d="${d}" fill="${fill}" />`;
  } catch {
    return null;
  }
}

/**
 * Measures the width of a string in pixels using the TTF metrics.
 */
function measureTextWidth(text, fontSize) {
  const font = getFont();
  if (!font) return text.length * fontSize * 0.6; // rough fallback
  try {
    return font.getAdvanceWidth(text, fontSize);
  } catch {
    return text.length * fontSize * 0.6;
  }
}

/**
 * Fetches an image, center-crops to square, adds a red bar with white text,
 * and returns a JPEG Buffer. Returns null on any failure so the caller can
 * fall back to the original URL.
 */
export async function cropToSquare(imageUrl, size = DEFAULT_SIZE, text = null) {
  if (!imageUrl) return null;

  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(new Error("Image fetch timeout")), FETCH_TIMEOUT_MS);

  let buffer;
  try {
    const res = await fetch(String(imageUrl), {
      signal: controller.signal,
      headers: { "user-agent": "Mozilla/5.0 (compatible; RDS-ImageProcess/1.0)" },
    });
    if (!res.ok) return null;
    buffer = Buffer.from(await res.arrayBuffer());
  } catch {
    return null;
  } finally {
    clearTimeout(t);
  }

  try {
    const barTop = size - BAR_HEIGHT;

    // Build SVG composited over the image.
    // The red bar is a plain rect; text is rendered as <path> elements
    // generated by opentype.js — no system fonts needed by librsvg.
    let textPaths = "";
    if (text) {
      const normalised = normaliseText(text);
      const lines = wrapText(normalised, 22, 2);
      const lineSpacing = FONT_SIZE + 10;
      const totalTextH = lines.length * lineSpacing;
      const baselineStart = barTop + Math.floor((BAR_HEIGHT - totalTextH) / 2) + FONT_SIZE;

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const lineWidth = measureTextWidth(line, FONT_SIZE);
        const x = Math.max(0, (size - lineWidth) / 2);
        const y = baselineStart + i * lineSpacing;
        const pathEl = textToSvgPath(line, x, y, FONT_SIZE, "white");
        if (pathEl) textPaths += pathEl + "\n";
      }
    }

    const svg = Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}">` +
      `<rect x="0" y="${barTop}" width="${size}" height="${BAR_HEIGHT}" fill="#c0161d" opacity="0.93"/>` +
      textPaths +
      `</svg>`
    );

    return await sharp(buffer)
      .resize(size, size, { fit: "cover", position: "centre" })
      .composite([{ input: svg, top: 0, left: 0 }])
      .jpeg({ quality: 85 })
      .toBuffer();
  } catch {
    return null;
  }
}
